// A reviewed phrase map for the static public presentation. A missing phrase fails the build.
// Keep the shared HTML structure and interactive hooks identical in both languages.
const phrases = {
  "QR ordering and shared bills for restaurants": "Comenzi prin QR și note împărțite pentru restaurante",
  "Order together.": "Comandați împreună.",
  "Pay your part.": "Fiecare își achită partea.",
  "Guests scan a table QR code, order on their phones and agree on shared dishes. Tablekind calculates what each person owes.": "Clienții scanează codul QR al mesei, comandă de pe telefon și confirmă preparatele împărțite. Tablekind calculează suma exactă pentru fiecare.",
  "For restaurants in Moldova: a focused view for waiters and managers to coordinate service.": "Pentru restaurantele din Moldova: interfețe clare pentru chelneri și manageri, ca să coordoneze servirea.",
  "Request a guided demo": "Solicită o demonstrație ghidată",
  "See how it works": "Vezi cum funcționează",
  "Prototype · TEST payments and POS only · No app or guest account required.": "Prototip · Plăți și POS doar de TEST · Fără aplicație sau cont obligatoriu pentru clienți.",
  "Scroll. Watch the table come together.": "Derulează și urmărește cum se adună masa.",
  "Made for the moments": "Creat pentru momentele",
  "around the table.": "petrecute la masă.",
  "Table 08": "Masa 08",
  "Welcome to the table": "Bine ai venit la masă",
  "Your kind": "O seară",
  "of evening.": "pe gustul tău.",
  "You": "Tu",
  "You + 2 friends": "Tu și încă 2 prieteni",
  "A favourite, shared three ways.": "Un preparat preferat, împărțit la trei.",
  "Your pizza share": "Partea ta din pizza",
  "Your lemonade": "Limonada ta",
  "Your part": "Partea ta",
  "Every share, accounted for.": "Fiecare parte este calculată.",
  "You’re at Table 08": "Ai intrat la masa 08",
  "Good food starts here.": "De aici începe masa.",
  "Shared, with a yes.": "Împărțit cu acordul tuturor.",
  "Everyone agrees to their part.": "Fiecare își confirmă partea.",
  "Your part. All clear.": "Partea ta. Totul e clar.",
  "Illustrative preview · Fictional table": "Ilustrație · Masă fictivă",
  "What Tablekind offers": "Ce oferă Tablekind",
  "One shared table.": "O masă împreună.",
  "Two clearer experiences.": "O experiență mai clară pentru toți.",
  "For guests": "Pentru clienți",
  "Enjoy the meal. Know your share.": "Bucură-te de masă. Știi cât îți revine.",
  "Scan the table QR and join in a browser, without an account.": "Scanezi codul QR al mesei și intri din browser, fără cont.",
  "Order for yourself and agree before sharing someone else’s item.": "Comanzi pentru tine și confirmi înainte să preiei o parte din comanda altcuiva.",
  "See your exact part of the bill, including shared dishes.": "Vezi suma exactă care îți revine, inclusiv din preparatele împărțite.",
  "For restaurants": "Pentru restaurante",
  "Keep service coordinated.": "Coordonează mai ușor servirea.",
  "Waiters review their tables, orders and requests in one view.": "Chelnerii urmăresc mesele, comenzile și solicitările într-o singură interfață.",
  "Managers set up menus, staff access, tables and printable QR codes.": "Managerii configurează meniuri, accesul echipei, mese și coduri QR imprimabile.",
  "Run a supervised pilot and measure use before planning live integrations.": "Testează într-un pilot supravegheat și măsoară utilizarea înainte de integrarea serviciilor reale.",
  "These flows are available in a guided fictional demo. Real payments, POS connections and bookings are not active.": "Aceste fluxuri pot fi văzute într-o demonstrație fictivă ghidată. Plățile reale, conexiunile POS și rezervările reale nu sunt active.",
  "Join without an account": "Intră fără cont",
  "Share by agreement": "Împarte cu acordul tuturor",
  "Know your part": "Știi cât îți revine",
  "The table, rethought": "O masă, regândită",
  "Together at the table.": "Împreună la masă.",
  "Clear on the details.": "Fiecare știe cât îi revine.",
  "Take a seat. Pick something to share. See how the details come together in this fictional evening.": "Așază-te, alege un preparat de împărțit și urmărește cum se calculează sumele în acest exemplu fictiv.",
  "Pull up a seat.": "Ia loc la masă.",
  "Join": "Intră",
  "Scan the table QR. Choose a nickname. You’re in.": "Scanează codul QR, alege un nume și intră la masă.",
  "A little for everyone.": "Câte puțin pentru fiecare.",
  "Share": "Împarte",
  "Order for yourself. Share an item when everyone agrees.": "Comandă pentru tine. Împarte un preparat când toți sunt de acord.",
  "Your part, made clear.": "Știi cât îți revine.",
  "Your bill": "Nota ta",
  "See the exact amount that belongs to you.": "Vezi suma exactă care îți revine.",
  "An interactive illustration, not a live table. No camera, account or payment is used.": "O ilustrație interactivă, nu o masă activă. Nu folosim camera, conturi sau plăți.",
  "An evening at Table 08": "O seară la masa 08",
  "PREVIEW": "PREVIZUALIZARE",
  "A seat for you. Room for everyone.": "Un loc pentru tine. Loc pentru toți.",
  "Your table": "Masa ta",
  "Joined Table 08": "Ai intrat la masa 08",
  "You’re in good company.": "Ești în companie bună.",
  "In the app: scan, confirm the table, then join with a nickname.": "În aplicație: scanezi, confirmi masa și intri cu un nume ales.",
  "Choose something to share": "Alege ce împărțiți",
  "One pizza. Three happy people.": "O pizza. Trei persoane mulțumite.",
  "Something for the middle": "Ce punem la mijloc",
  "Vegetables": "Legume",
  "Chocolate cake": "Tort de ciocolată",
  "Set the places": "Alege numărul de persoane",
  "2 guests": "2 persoane",
  "3 guests": "3 persoane",
  "4 guests": "4 persoane",
  "One dish, shared by agreement.": "Un preparat împărțit cu acordul tuturor.",
  "Three equal shares.": "Trei părți egale.",
  "Agreed ✓": "Confirmat ✓",
  "120 MDL ÷ 3 = 40 MDL each": "120 MDL ÷ 3 = 40 MDL de persoană",
  "A lemonade, just for you.": "O limonadă doar pentru tine.",
  "35 MDL · Your drink stays on your share.": "35 MDL · Băutura ta rămâne în partea ta.",
  "40 shared food + 35 lemonade": "40 preparat împărțit + 35 limonadă",
  "See your bill": "Vezi nota ta",
  "The example assumes everyone agrees. Real sharing requests require each guest’s consent.": "În exemplu, toți acceptă. Solicitările reale de împărțire cer acordul fiecărui client.",
  "No mental maths required.": "Fără calcule pe șervețel.",
  "Your part · Table 08": "Partea ta · Masa 08",
  "Lemonade · Just for you": "Limonadă · Doar pentru tine",
  "Your total": "Totalul tău",
  "Fictional amounts. No money is collected.": "Sume fictive. Nu se încasează bani.",
  "Only your part comes with you.": "Îți revine doar partea ta.",
  "The pizza is shared. Your lemonade is yours.": "Pizza e împărțită. Limonada este a ta.",
  "Try another combination": "Încearcă altă combinație",
  "Reset example": "Resetează exemplul",
  "Live payments and POS connections require future provider and restaurant agreements.": "Plățile și conexiunile POS reale necesită acorduri viitoare cu furnizorii și restaurantele.",
  "For the people behind the service": "Pentru echipa restaurantului",
  "Thoughtful for guests.": "Simplu pentru clienți.",
  "Practical for your team.": "Util pentru echipă.",
  "Not another screen for everyone to manage. A focused space for each role, from the dining room to the manager’s desk.": "Fiecare rol are o interfață dedicată, de la sala restaurantului până la activitatea managerului.",
  "01 / Service": "01 / Servire",
  "The right view.": "Informația potrivită.",
  "For the right person.": "Pentru persoana potrivită.",
  "Guests see their table. Waiters focus on service. Managers handle restaurant settings.": "Clienții văd masa lor. Chelnerii se ocupă de servire. Managerii gestionează setările restaurantului.",
  "One table. A different view for each person.": "O masă. O interfață potrivită fiecărui rol.",
  "Guest": "Client",
  "Waiter": "Chelner",
  "Manager": "Manager",
  "Illustrative guest view": "Interfață ilustrativă pentru client",
  "My evening, my way.": "Seara mea, în ritmul meu.",
  "Join a table, order favourites and see your own share.": "Intră la masă, comandă ce îți place și vezi cât îți revine.",
  "My order": "Comanda mea",
  "My share": "Partea mea",
  "Margherita · My share": "Margherita · Partea mea",
  "Lemonade": "Limonadă",
  "My part": "Partea mea",
  "02 / Setup": "02 / Configurare",
  "Table": "Masa",
  "Start with your tables.": "Începe cu mesele tale.",
  "A basic menu, staff access and printable table QR codes. Setup we can walk through together.": "Un meniu de bază, acces pentru echipă și coduri QR imprimabile pentru mese. Putem parcurge configurarea împreună.",
  "03 / Learning": "03 / Învățare",
  "Learn from a real pilot.": "Învață dintr-un pilot real.",
  "Aggregate activity counts help us understand use. Actual restaurant outcomes still need to be measured.": "Numărul agregat de activități ne ajută să înțelegem utilizarea. Rezultatele reale într-un restaurant trebuie încă măsurate.",
  "A clear starting point": "Un punct clar de plecare",
  "A working prototype.": "Un prototip funcțional.",
  "A thoughtful next step.": "Următorul pas, împreună.",
  "The working prototype covers table joining, ordering, shared-bill coordination and separate staff interfaces. We’re looking for restaurant conversations to shape a supervised pilot.": "Prototipul funcțional include intrarea la masă, comenzile, coordonarea notei împărțite și interfețe separate pentru echipă. Căutăm restaurante cu care să discutăm un posibil pilot supravegheat.",
  "Available to demonstrate": "Disponibil pentru demonstrație",
  "Fictional ordering, sharing and exact individual amounts.": "Comenzi fictive, împărțirea preparatelor și sume individuale exacte.",
  "Not connected to live services": "Fără conexiuni la servicii reale",
  "Payments and POS remain TEST simulators. Reservations are practice-only. No bank, MIA, terminal or fiscal integration is active.": "Plățile și POS-ul rămân simulatoare de TEST. Rezervările sunt doar exerciții. Nu există integrare activă cu bănci, MIA, terminale sau sisteme fiscale.",
  "Read the pilot information": "Citește informațiile despre pilot",
  "A few things worth knowing": "Câteva lucruri de știut",
  "Before we sit down.": "Înainte să discutăm.",
  "Do guests need an app or an account?": "Clienții au nevoie de aplicație sau cont?",
  "No app installation is needed. The prototype works in the browser, and guests can join a table without creating an account. Accounts are optional.": "Nu trebuie instalată o aplicație. Prototipul funcționează în browser, iar clienții pot intra la masă fără cont. Conturile sunt opționale.",
  "Can my restaurant start using it today?": "Restaurantul meu poate începe să îl folosească azi?",
  "We can arrange a guided fictional demonstration first. A live pilot needs an agreed workflow, access controls, operational checks and any required integrations. This website does not activate restaurant service.": "Putem începe cu o demonstrație fictivă ghidată. Un pilot operațional necesită un flux convenit, controlul accesului, verificări și integrările necesare. Acest site nu activează serviciul în restaurant.",
  "Does Tablekind replace our existing POS?": "Tablekind înlocuiește POS-ul existent?",
  "No. Your restaurant’s workflow and POS must be assessed before a pilot. The current POS connector is a TEST simulator, not a connection to a commercial POS or fiscal system.": "Nu. Fluxul restaurantului și POS-ul trebuie evaluate înaintea unui pilot. Conectorul actual este un simulator de TEST, fără conexiune la un POS comercial sau fiscal.",
  "What does it cost?": "Cât costă?",
  "Restaurant pricing and pilot terms have not been finalised. We want to understand the restaurant’s needs first. An enquiry is not a subscription or a payment commitment.": "Prețurile și condițiile pilotului nu sunt stabilite. Mai întâi vrem să înțelegem nevoile restaurantului. O solicitare nu înseamnă abonament sau obligație de plată.",
  "Can I try the full demo?": "Pot încerca demonstrația completă?",
  "Yes, by arrangement. The guided application demo uses fictional tables, orders and payments. It stays separate from this presentation site and from future restaurant accounts.": "Da, cu programare. Demonstrația ghidată folosește mese, comenzi și plăți fictive. Este separată de acest site de prezentare și de viitoarele conturi ale restaurantelor.",
  "Let’s build a better table experience": "Hai să îmbunătățim experiența la masă",
  "Your restaurant.": "Restaurantul tău.",
  "Our next": "Următoarea noastră",
  "conversation.": "discuție.",
  "Tell us how your service works.": "Spune-ne cum funcționează servirea la tine.",
  "We’ll show you where Tablekind could fit.": "Îți arătăm unde s-ar potrivi Tablekind.",
  "Let’s talk about your restaurant": "Hai să vorbim despre restaurantul tău",
  "No commitment. No sales checkout. Just a conversation.": "Fără obligații și fără plată. Doar o discuție.",
  "How it works": "Cum funcționează",
  "Let’s talk": "Hai să discutăm",
  "Menu": "Meniu",
  "Pull up a seat": "Ia loc la masă",
  "About the pilot": "Despre pilot",
  "A little less counting.": "Mai puține calcule.",
  "A little more company.": "Mai mult timp împreună.",
  "Built with Moldova in mind · {{YEAR}}": "Creat pentru Moldova · {{YEAR}}",
  "Contact": "Contact",
  "Pilot information": "Informații despre pilot",
  "Privacy": "Confidențialitate",
  "Pre-launch prototype. Payments and POS are TEST simulators. No real money, kitchen orders or table bookings are processed.": "Prototip înainte de lansare. Plățile și POS-ul sunt simulatoare de TEST. Nu se procesează bani reali, comenzi reale către bucătărie sau rezervări de mese.",
  "Where we are today": "Unde suntem acum",
  "A pilot starts with": "Un pilot începe cu",
  "a clear plan.": "un plan clar.",
  "This page describes the prototype and a possible next step. It is not a restaurant service agreement.": "Această pagină descrie prototipul și un posibil pas următor. Nu reprezintă un acord de furnizare a serviciului către restaurante.",
  "What we can demonstrate": "Ce putem demonstra",
  "The working application includes table QR joining, individual orders, shared-item consent, exact individual shares and separate guest, waiter, manager and private platform-administration interfaces. Optional customer accounts use local TEST email in the existing demo.": "Aplicația funcțională include acces la masă prin QR, comenzi individuale, acordul pentru preparate împărțite, sume exacte pentru fiecare și interfețe separate pentru clienți, chelneri, manageri și administrarea privată a platformei. Conturile opționale folosesc email local de TEST în demonstrația existentă.",
  "What the demonstration does not do": "Ce nu face demonstrația",
  "Payments and POS connections are TEST simulators. No real card, MIA, bank, terminal or fiscal integration exists. Do not use real money, payment details or customer data in the demonstration.": "Plățile și conexiunile POS sunt simulatoare de TEST. Nu există integrări reale cu carduri, MIA, bănci, terminale sau sisteme fiscale. Nu folosi bani reali, date de plată sau date despre clienți în demonstrație.",
  "Reservation exercises are fictional. They do not reserve capacity or book a real restaurant table. This presentation website cannot place an order, scan a live table QR, register restaurant staff or activate restaurant access.": "Exercițiile de rezervare sunt fictive: nu rezervă locuri sau mese într-un restaurant real. Acest site de prezentare nu poate plasa comenzi, scana coduri QR ale unor mese active, înregistra angajați sau activa accesul unui restaurant.",
  "Before a restaurant pilot": "Înainte de un pilot într-un restaurant",
  "Agree the specific problem, restaurant workflow, participants and success measures.": "Stabilim problema concretă, fluxul restaurantului, participanții și criteriile de succes.",
  "Choose whether the trial is a fictional practice session or a separately approved operational pilot.": "Alegem dacă testul este o sesiune fictivă sau un pilot operațional aprobat separat.",
  "Confirm access permissions, staff training, privacy responsibilities and a fallback to the existing restaurant process.": "Confirmăm drepturile de acces, instruirea echipei, responsabilitățile privind datele și revenirea la procesul existent.",
  "Review hosting, backups, restoration and support arrangements.": "Verificăm găzduirea, copiile de siguranță, restaurarea și suportul.",
  "Implement and validate any required real payment, POS or fiscal connections before relying on them.": "Implementăm și validăm orice integrare necesară cu plăți, POS sau sisteme fiscale înainte să ne bazăm pe ea.",
  "Access and pricing": "Acces și prețuri",
  "The full fictional demo is arranged privately. An enquiry is not automatic acceptance, a subscription or an obligation to pay. Pilot timing, scope and commercial terms must be agreed separately. Restaurant pricing has not been finalised.": "Demonstrația fictivă completă se oferă prin invitație privată. O solicitare nu înseamnă acceptare automată, abonament sau obligație de plată. Perioada, scopul și termenii comerciali ai pilotului se stabilesc separat. Prețurile pentru restaurante nu sunt definitive.",
  "Built with feedback, not assumptions": "Construim cu feedback și verificări",
  "We have not yet validated outcomes in a live restaurant. A controlled pilot should measure the actual table experience and staff workload. We do not promise a particular revenue increase, time saving or compatibility with your current POS.": "Nu am validat încă rezultatele într-un restaurant real. Un pilot controlat trebuie să măsoare experiența la masă și volumul de muncă al personalului. Nu promitem creșterea veniturilor, economii de timp sau compatibilitate cu POS-ul existent.",
  "Start the conversation": "Începe discuția",
  "For restaurant owners and teams": "Pentru proprietari și echipele restaurantelor",
  "Let’s start with": "Să începem cu",
  "your table.": "masa ta.",
  "Tell us a little about your restaurant. We can explore the prototype together and discuss what a useful pilot would look like.": "Spune-ne câteva lucruri despre restaurantul tău. Putem explora prototipul împreună și discuta cum ar arăta un pilot util.",
  "A conversation, not a commitment.": "O discuție, fără obligații.",
  "Tell us how service works at your restaurant.": "Ne spui cum funcționează servirea în restaurant.",
  "We walk through a fictional table together.": "Parcurgem împreună un exemplu de masă fictivă.",
  "If there’s a fit, we agree the scope of a supervised pilot.": "Dacă se potrivește, stabilim scopul unui pilot supravegheat.",
  "No subscription, no payment details and no automatic restaurant registration.": "Fără abonament, date de plată sau înregistrare automată a restaurantului.",
  "{{CONTACT_DIRECT}}": "{{CONTACT_DIRECT}}",
  "Please don’t include customer information, passwords or financial records.": "Nu include date despre clienți, parole sau documente financiare.",
  "The optional draft composer needs JavaScript. You can contact us directly when the published contact address is available. No form data will be submitted here.": "Instrumentul opțional pentru ciornă necesită JavaScript. Ne poți contacta direct când adresa publică va fi disponibilă. Formularul nu trimite date.",
  "Prepare a demo enquiry": "Pregătește o solicitare de demonstrație",
  "Your name": "Numele tău",
  "Restaurant": "Restaurant",
  "City": "Oraș",
  "What would you like to explore?": "Ce ai vrea să discutăm?",
  "Optional · Up to 600 characters": "Opțional · Maximum 600 de caractere",
  "This prepares a draft on your device. It does not submit a request. You choose whether to send it from your own email app.": "Se pregătește o ciornă pe dispozitivul tău. Solicitarea nu este trimisă. Tu alegi dacă o trimiți prin aplicația ta de email.",
  "How your information is used": "Cum sunt folosite informațiile tale",
  "Prepare my enquiry": "Pregătește solicitarea",
  "Your draft is ready. Not sent.": "Ciorna este gata. Nu a fost trimisă.",
  "Review the text below. If you change the form, prepare a new draft.": "Verifică textul de mai jos. Dacă modifici formularul, pregătește o ciornă nouă.",
  "Email draft": "Ciornă de email",
  "Open my email app": "Deschide aplicația de email",
  "Copy draft": "Copiază ciorna",
  "Clear form": "Golește formularul",
  "Public presentation website": "Site public de prezentare",
  "A little information.": "Puține informații.",
  "A clear purpose.": "Un scop clar.",
  "This notice describes the public website and demo enquiries, not the separate restaurant application.": "Această informare descrie site-ul public și solicitările de demonstrație, nu aplicația separată pentru restaurante.",
  "Who operates this website": "Cine administrează site-ul",
  "{{OPERATOR}}": "{{OPERATOR}}",
  "Contact: {{CONTACT_EMAIL}}": "Contact: {{CONTACT_EMAIL}}",
  "Browsing the website": "Navigarea pe site",
  "The supplied website does not add analytics, advertising, tracking cookies, local storage or session storage. Its illustrations and fonts are served locally or provided by your device. The walkthrough does not access your camera or any restaurant system.": "Acest site nu adaugă instrumente de analiză, reclame, cookie-uri de urmărire sau stocare locală ori de sesiune. Ilustrațiile și fonturile provin din site sau de pe dispozitivul tău. Exemplul interactiv nu accesează camera sau sistemele vreunui restaurant.",
  "Website hosting necessarily processes connection information, such as an IP address, to serve requests. Hosting provider: {{HOSTING}} {{HOSTING_LINK}} The provider’s processing and retention are separate from the email enquiry policy below.": "Găzduirea site-ului necesită prelucrarea unor informații de conectare, precum adresa IP, pentru a livra paginile. Furnizorul de găzduire: {{HOSTING}} {{HOSTING_LINK}} Prelucrarea și păstrarea datelor de către furnizor sunt separate de regulile privind solicitările prin email de mai jos.",
  "Preparing an enquiry": "Pregătirea unei solicitări",
  "The name, restaurant, city and optional message you type remain in the page while you prepare a draft. They are not submitted to a website server by this form. You can clear them using Clear form after preparing a draft. Your browser may have its own autofill or page-restoration behaviour.": "Numele, restaurantul, orașul și mesajul opțional rămân în pagină când pregătești ciorna. Formularul nu le trimite unui server. Le poți șterge prin butonul „Golește formularul”. Browserul poate completa sau restaura singur câmpurile.",
  "Copy draft writes the draft to your device clipboard only when you select that button. Open my email app passes the draft to your email application. You must review and send it there. The website cannot see whether the message was sent or delivered.": "Butonul „Copiază ciorna” scrie textul în clipboardul dispozitivului doar când îl apeși. „Deschide aplicația de email” transmite ciorna aplicației tale de email. Trebuie să o verifici și să o trimiți de acolo. Site-ul nu poate confirma trimiterea sau livrarea.",
  "If you send an email": "Dacă trimiți un email",
  "The recipient and email providers process your email address and any details you include so we can respond to your enquiry and discuss a demonstration. Please share only what is necessary. Do not send customer records, access tokens, passwords or payment details.": "Destinatarul și furnizorii de email prelucrează adresa ta și detaliile incluse pentru a putea răspunde și discuta demonstrația. Trimite doar informațiile necesare. Nu trimite date despre clienți, tokenuri de acces, parole sau informații de plată.",
  "Enquiry retention: {{RETENTION}} Please contact the operator to ask about access, correction or deletion of your enquiry. A pilot involving additional information will need a separate agreed notice and process.": "Păstrarea solicitării: {{RETENTION}} Contactează operatorul dacă dorești acces, corectare sau ștergerea solicitării. Un pilot care implică alte date va necesita o informare și un proces convenite separat.",
  "What this notice does not cover": "Ce nu acoperă această informare",
  "The private application demo, future restaurant service and any third-party email or hosting service have their own data flows. This static presentation does not activate guest account verification or collect phone numbers for SMS.": "Demonstrația privată a aplicației, viitorul serviciu pentru restaurante și serviciile terțe de email sau găzduire au fluxuri de date proprii. Acest site static nu activează verificarea conturilor de client și nu colectează numere de telefon pentru SMS.",
  "Website notice version: Phase 11, September 2026. The operator must confirm the contact, hosting and retention details before publication.": "Versiunea informării: Faza 11, septembrie 2026. Operatorul trebuie să confirme datele de contact, găzduire și păstrare înainte de publicare.",
  "404 · Wrong table": "404 · Masă greșită",
  "This page has": "Pagina aceasta",
  "stepped out.": "a ieșit din meniu.",
  "The public website doesn’t host restaurant login, management or ordering. If you have a private demo invitation, use the address shared with you.": "Site-ul public nu găzduiește autentificarea restaurantelor, managementul sau comenzile. Dacă ai invitație la demonstrația privată, folosește adresa primită.",
  "Back to Tablekind": "Înapoi la Tablekind",
  "Contact us": "Contactează-ne",
  "Tablekind home": "Pagina principală Tablekind",
  "Main navigation": "Navigație principală",
  "Footer": "Subsol",
  "Product principles": "Principiile produsului",
  "Choose a walkthrough step": "Alege un pas din exemplu",
  "Fictional table walkthrough": "Exemplu de masă fictivă",
  "Three fictional guests": "Trei clienți fictivi",
  "Explore the role previews": "Explorează interfețele pentru roluri",
  "Fictional product illustration: at Table 08, one third of a pizza is 40 MDL, lemonade is 35 MDL, and your total share is 75 MDL. No payment is made.": "Ilustrație fictivă: la masa 08, o treime din pizza este 40 MDL, limonada este 35 MDL, iar partea ta totală este 75 MDL. Nu se efectuează plăți.",
  "For example: handling shared dishes at a busy table.": "De exemplu: împărțirea preparatelor la o masă aglomerată.",
};

const unchanged = new Set(["t", "k", "tablekind.", "tablekind", "MDL", "Margherita", "Alex", "Sam", "S", "M", "W", "G", "A", "⅓ Margherita"]);

export function translateRomanian(html) {
  const translate = (value) => {
    const clean = value.replace(/\s+/g, " ").trim();
    if (!clean || !/[A-Za-zÀ-ÿăâîșțĂÂÎȘȚ]/u.test(clean)) return value;
    if (unchanged.has(clean) || /^\d+(?: MDL)?$/.test(clean) || /^\{\{[A-Z_]+\}\}$/.test(clean)) return value;
    if (!Object.hasOwn(phrases, clean)) throw new Error(`Missing Romanian phrase: ${clean}`);
    const [, before, , after] = value.match(/^(\s*)([\s\S]*?)(\s*)$/);
    return before + phrases[clean] + after;
  };
  return html
    .replace(/>([^<>]+)</g, (_, value) => `>${translate(value)}<`)
    .replace(/(aria-label|placeholder|title)="([^"]+)"/g, (_, name, value) => `${name}="${translate(value)}"`)
    .replace(/href="\/(?!ro\/|assets\/)([^"#]*)/g, (_, path) => `href="/ro/${path}`);
}
